"""Export the numerical parity fixture the Rust core is tested against.

Phase 3 ports this detector to Rust. The port is only meaningful if there is a
fixed, committed artifact saying what the reference produces — otherwise "parity"
degrades into running both implementations and believing whichever looks right.

So the fixture is written **before** any Rust exists, from the frozen reference,
and committed to git. `cargo test` must be able to replay it in a fresh clone with
no Python step and no generated data.

## What is in it

- the exact `DetectorConfig` the scores were produced under, so a mismatch in
  window size or a weight fails loudly instead of showing up as a tolerance
  problem
- the event stream, carrying **only** `FEATURE_COLUMNS` — no labels, no scenario
  ids. The Rust core never sees them, so the fixture that defines its contract
  should not contain them either
- one expected score per event, in order

## Why a purpose-built stream rather than a slice of the shipped one

Parity needs a contiguous run from a cold start, because the detector is a state
machine and a slice from the middle would need its state seeded. A dedicated small
config gives a fixture that starts cold, exercises all six scenarios, and stays
small enough to commit.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path

from ..gen.build import generate_events
from ..gen.config import GenConfig, ScenarioEpisodeSpec
from ..gen.schema import FEATURE_COLUMNS
from .interface import DetectorConfig
from .reference import ReferenceDetector

FIXTURE_PATH = Path("tests/fixtures/parity.json")

#: A compact stream that touches every scenario. Deliberately small: the fixture
#: is committed, so it has to stay reviewable in a diff.
PARITY_CONFIG = GenConfig(
    seed=7_314_159,
    total_days=1,
    train_days=1,
    merchant_count=2,
    benign_card_pool_size=600,
    benign_ip_pool_size=450,
    benign_device_pool_size=400,
    benign_bin_pool_size=24,
    episodes=(
        ScenarioEpisodeSpec("burst", 0.16, 9.0, 110, 110, 1, 1, 0.86, 100, 5_000, 0),
        ScenarioEpisodeSpec("rotating", 0.31, 20.0, 100, 100, 26, 24, 0.84, 100, 5_000, 1),
        ScenarioEpisodeSpec("slow_low", 0.44, 150.0, 36, 36, 3, 3, 0.72, 100, 3_000, 0),
        ScenarioEpisodeSpec("flash_sale", 0.58, 35.0, 150, 145, 140, 135, 0.16, 20_000, 900_000, 1),
        ScenarioEpisodeSpec("issuer_outage", 0.72, 45.0, 160, 52, 50, 48, 0.83, 1_000, 500_000, 0, 2),
        ScenarioEpisodeSpec("outage_single_merchant", 0.86, 40.0, 160, 34, 32, 30, 0.82, 100, 6_000, 1),
        # The saturating mega-burst. 900 events in 4 minutes on one BIN, one IP,
        # one device, one merchant: every axis's ring buffer (capacity 512)
        # overflows inside a single 5-minute window. Phase 3 review found the
        # original fixture never filled a ring - peak occupancy was 58 of 512 -
        # so parity had verified the happy path and said nothing about the
        # wraparound bookkeeping (the forget-on-push path and its interaction
        # with later time-eviction), which is one of the two places a Rust
        # reimplementation of a Python deque actually drifts. Benign traffic on
        # the same merchant afterwards then drains the saturated windows through
        # evict_before, covering the interaction too.
        ScenarioEpisodeSpec("burst", 0.93, 4.0, 900, 900, 1, 1, 0.87, 100, 5_000, 0),
    ),
)

#: Absolute tolerance the Rust core must meet, per event.
#:
#: Not zero. The reference accumulates in f64 through Welford and an EWMA, and a
#: Rust port doing the same arithmetic in a different order can differ in the last
#: bits. 1e-9 is far tighter than anything that could change a flag decision at a
#: threshold near 22, and loose enough not to fail on summation order.
#:
#: If parity cannot be met at this tolerance by the end of day one of Phase 3, the
#: pre-committed escape hatch applies: ship with the achieved tolerance documented
#: here and a BUILD_LOG entry naming the discrepancy. No second day on parity.
TOLERANCE = 1e-9


def build_fixture(
    gen_config: GenConfig = PARITY_CONFIG,
    detector_config: DetectorConfig | None = None,
) -> dict:
    detector_config = detector_config or DetectorConfig()
    events = generate_events(gen_config)
    scores = ReferenceDetector(detector_config).score_batch(events)

    return {
        "_comment": (
            "Numerical parity fixture for spandan-core. Generated by "
            "`python -m spandan.detect.parity`. Committed deliberately: cargo test "
            "must run in a fresh clone with no Python step."
        ),
        "tolerance": TOLERANCE,
        "detector_config": asdict(detector_config),
        "feature_columns": list(FEATURE_COLUMNS),
        "events": [
            [getattr(event, name) for name in FEATURE_COLUMNS] for event in events
        ],
        "expected_scores": [float(score) for score in scores],
    }


def serialise(fixture: dict) -> str:
    """Compact, but one record per line so a diff is still readable.

    Events are arrays keyed by `feature_columns` rather than objects: at ~7k
    events the object form cost 2.2MB, most of it repeated key names, for a file
    that has to live in git.
    """
    head = {k: v for k, v in fixture.items() if k not in ("events", "expected_scores")}
    lines = [json.dumps(head, sort_keys=True)[:-1] + ","]
    lines.append(' "events": [')
    lines.extend(
        "  " + json.dumps(row, separators=(",", ":")) + ("," if i < len(fixture["events"]) - 1 else "")
        for i, row in enumerate(fixture["events"])
    )
    lines.append(" ],")
    lines.append(' "expected_scores": [')
    scores = fixture["expected_scores"]
    lines.extend(
        "  " + repr(value) + ("," if i < len(scores) - 1 else "")
        for i, value in enumerate(scores)
    )
    lines.append(" ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def serialise_tsv(fixture: dict) -> str:
    """The same fixture in a format Rust can read with `std` alone.

    PHASES.md Phase 3 approves exactly one new Rust crate — `proptest` — and says
    "nothing else". A JSON fixture would need `serde_json` to read, so rather than
    spend the project's one dependency request on a test reader, or hand-roll a
    JSON parser (fragile, and precisely the kind of thing a reviewer should
    question), the same builder emits a tab-separated twin.

    `parity.json` remains the canonical committed artifact named in the plan and
    is what a human reads. `parity.tsv` is derived from the identical `build_fixture`
    output, and `test_parity_json_and_tsv_agree` asserts they carry the same data,
    so the two cannot drift.

    Layout, chosen so the Rust reader is a `split('\\t')` and nothing more:

        tolerance <TAB> 1e-09
        config    <TAB> window_ms=300000 <TAB> ring_capacity=512 <TAB> ...
        columns   <TAB> ts <TAB> txn_id <TAB> ... <TAB> expected_score
        <one event per line, fields in `columns` order, score last>
    """
    config = fixture["detector_config"]
    lines = [
        f"tolerance\t{fixture['tolerance']!r}",
        "config\t" + "\t".join(f"{k}={_tsv_scalar(v)}" for k, v in sorted(config.items())),
        "columns\t" + "\t".join(fixture["feature_columns"]) + "\texpected_score",
    ]
    for row, score in zip(fixture["events"], fixture["expected_scores"]):
        cells = [str(value) for value in row]
        lines.append("\t".join(cells) + "\t" + repr(score))
    return "\n".join(lines) + "\n"


def _tsv_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return repr(value) if isinstance(value, float) else str(value)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write the Rust parity fixture.")
    parser.add_argument("--out", default=str(FIXTURE_PATH))
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate and compare instead of writing; non-zero if it would change",
    )
    args = parser.parse_args(argv)

    fixture = build_fixture()
    payload = serialise(fixture)
    out = Path(args.out)
    tsv_out = out.with_suffix(".tsv")
    tsv_payload = serialise_tsv(fixture)

    if args.check:
        for path, expected in ((out, payload), (tsv_out, tsv_payload)):
            if not path.exists():
                print(f"{path} does not exist")
                return 1
            if path.read_text(encoding="utf-8") != expected:
                print(f"{path} is STALE - the reference detector changed since it was written")
                return 1
        print(f"{out} and {tsv_out} are current ({len(fixture['events'])} events)")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(payload, encoding="utf-8")
    tsv_out.write_text(tsv_payload, encoding="utf-8")
    print(f"wrote {out} and {tsv_out}  ({len(fixture['events'])} events, tolerance {TOLERANCE:g})")
    print(f"detector window_ms={fixture['detector_config']['window_ms']} "
          f"ring_capacity={fixture['detector_config']['ring_capacity']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
